### ISSUE TITLE
ImportError for EigenSolvers

### ISSUE THREAD

**Issue by bikhanal** [manurare/360monodepth#14]
Thank you for this amazing work. I successfully installed everything with the help of Dockerfile. However, when I ran the main.py code, I got following error everytime. I tried recompiling everything but still got same error.

```bash
root@55d28786ec5a:/monodepth/code/python/src# python3 main.py 
Adding '/monodepth/code/python/src' to sys.path
2023-02-10 08:01:56,106 - utility.depthmap_align - INFO - depthmapAlign python module installed!
Traceback (most recent call last):
  File "/monodepth/code/python/src/main.py", line 17, in <module>
    from utility import blending
  File "/monodepth/code/python/src/utility/blending.py", line 6, in <module>
    from EigenSolvers import LinearSolver
ImportError: /monodepth/code/cpp/lib/EigenSolvers.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN6google10LogMessage6streamEv
root@55d28786ec5a:/monodepth/code/python/src#
``` 

Can you help me with this? Thank you.

**Comment by manurare** [comment]
Hey,

That symbol belong to `glog` I think. So it might be that glog did not installed or that it is not the exact version we tested with `Glog 0.5.0`.

**Comment by bikhanal** [comment]
@manurare Thanks, the `glog` seems to be of right version since I followed the instruction for docker. I suspect it may be caused due to python version. I will check and let you know.

**Comment by rayryeng** [comment]
I had the same issue. What worked for me was that I had to modify the CMakeLists.txt file because I am using a more recent version of CMake, so instead of finding the `glog` libraries with `${GLOG_LIBRARIES}`, I replaced the target with `glog::glog` as this will handle finding the include directories and definitions. As such, I simply replaced anywhere I found `${GLOG_LIBRARIES}` with `glog::glog`. I also did the same with the Ceres targets, so changing `${CERES_LIBRARIES}` to `Ceres::ceres`.
